import {Feature as GeoJsonFeature, Geometry, LineString, Point, Polygon} from "geojson"

export interface Door {
    type: DOOR_TYPE | null,
    automatic: boolean,
    material: "wood" | "glass" | "metal" | "gate" | null
}

interface FeatureReference {
    id: FeatureId,
    feature_type: FeatureType
}

export enum FeatureType {
    "address"="address",
    "amenity"="amenity",
    "anchor"="anchor",
    "building"="building",
    "detail"="detail",
    "fixture"="fixture",
    "footprint"="footprint",
    "geofence"="geofence",
    "kiosk"="kiosk",
    "level"="level",
    "occupant"="occupant",
    "opening"="opening",
    "relationship"="relationship",
    "section"="section",
    "unit"="unit",
    "venue"="venue"
}

export interface Labels {
    [key: string]: string; // ToDo Restrict key to lang shortnames
}

export interface Temporality {
    start: string,
    end: string,
    modified: string
}

export type Hours = string
export type Phone = string
export type Website = string
export type ISO3166 = string
export type ISO3166_2 = string

// IDS
export type FeatureId = string
export type AddressId = FeatureId
export type AmenityId = FeatureId
export type AnchorId = FeatureId
export type BuildingId = FeatureId
export type DetailId = FeatureId
export type FixtureId = FeatureId
export type FootprintId = FeatureId
export type GeofenceId = FeatureId
export type KioskId = FeatureId
export type LevelId = FeatureId
export type OccupantId = FeatureId
export type RelationshipId = FeatureId
export type SectionId = FeatureId
export type UnitId = FeatureId
export type VenueId = FeatureId

/**
 * Base properties for all IMDF features
 */
export type FeatureProperties = {};

/**
 * Provide a better default value for GeoJsonFeature (Feature in geojson).
 * This makes the type Feature to be used in generic types much easier.
 */
export interface Feature<P extends FeatureProperties> extends GeoJsonFeature<Geometry | null, FeatureProperties> {
    feature_type: string
}

export interface NamedFeatureProperties extends Properties {
    name: Labels | null,
    alt_name?: Labels | null,
    display_point?: DisplayPoint | null
}

export interface LabeledFeatureProperties extends NamedFeatureProperties {
    level_id: LevelId,
    display_point: DisplayPoint | null
}

/**
 * Features that have a name
 */
export interface NamedFeature<Properties extends NamedFeatureProperties = NamedFeatureProperties> extends Feature<Properties> {}

/**
 * Features that have a name and a label position
 */
export interface LabeledFeature<Properties extends LabeledFeatureProperties = LabeledFeatureProperties> extends NamedFeature<Properties> {}

// FEATURE TYPES
/**
 * Address object
 * https://docs.ogc.org/cs/20-094/Address/index.html
 */
export interface Address extends Feature {
    id: AddressId,
    feature_type: FeatureType.address,
    geometry: null,
    properties: FeatureProperties & {
        address: string,
        unit: string | null,
        locality: string,
        province: ISO3166_2 | null,
        country: ISO3166,
        postal_code: string | null,
        postal_code_ext: string | null,
        postal_code_vanity: string | null
    }
}

/**
 * Amenity object
 * https://docs.ogc.org/cs/20-094/Amenity/index.html
 */
export interface Amenity extends NamedFeature {
    id: AmenityId,
    feature_type: FeatureType.amenity,
    geometry: Point,
    properties: FeatureProperties & {
        category: AMENITY_CATEGORY,
        accessibility: ACCESSIBILITY_CATEGORY | null,
        name: Labels | null,
        alt_name: Labels | null,
        hours: Hours | null,
        phone: Phone | null,
        website: Website | null,
        unit_ids: Array<UnitId>,
        address_id: AddressId | null,
        correlation_id: AmenityId | null
    }
}

/**
 * Anchor object
 * https://docs.ogc.org/cs/20-094/Anchor/index.html
 */
export interface Anchor extends Feature {
    id: AnchorId,
    feature_type: FeatureType.anchor,
    geometry: Point,
    properties: FeatureProperties & {
        address_id: AddressId | null,
        unit_id: UnitId
    }
}

export interface BuildingProperties extends NamedFeatureProperties {
    category: BUILDING_CATEGORY,
    restriction: RESTRICTION_CATEGORY,
    name: Labels | null,
    alt_name: Labels | null,
    display_point: DisplayPoint | null,
    address_id: AddressId | null
}

/**
 * Building object
 * https://docs.ogc.org/cs/20-094/Building/index.html
 */
export interface Building extends NamedFeature<BuildingProperties> {
    id: BuildingId,
    feature_type: FeatureType.building,
    geometry: null,
    properties: BuildingProperties
}

/**
 * Detail object
 * https://docs.ogc.org/cs/20-094/Detail/index.html
 */
export interface Detail extends Feature {
    id: DetailId,
    feature_type: FeatureType.detail,
    properties: FeatureProperties & {
        level_id: LevelId
    }
}

/**
 * Fixture object
 * https://docs.ogc.org/cs/20-094/Fixture/index.html
 */
export interface Fixture extends LabeledFeature {
    id: FixtureId,
    feature_type: FeatureType.fixture,
    geometry: Polygon,
    properties: FeatureProperties & {
        category: FIXTURE_CATEGORY,
        name: Labels | null,
        alt_name: Labels | null,
        anchor_id: AnchorId | null,
        level_id: LevelId,
        display_point: DisplayPoint | null
    }
}

/**
 * Footprint object
 * https://docs.ogc.org/cs/20-094/Footprint/index.html
 */
export interface Footprint {
    id: FootprintId,
    feature_type: FeatureType.footprint,
    geometry: Polygon,
    properties: FeatureProperties & {
        category: FOOTPRINT_CATEGORY,
        name: Labels | null,
        building_ids: Array<BuildingId>
    }
}

/**
 * Geofence object
 * https://docs.ogc.org/cs/20-094/Geofence/index.html
 */
export interface Geofence extends Feature {
    id: GeofenceId,
    feature_type: FeatureType.geofence,
    geometry: Polygon,
    properties: FeatureProperties & {
        category: GEOFENCE_CATEGORY
    }
}

export interface KioskProperties extends NamedFeatureProperties {
    name: Labels,
    alt_name: Labels,
    anchorId: AnchorId | null
    levelId: LevelId | null
    display_point: DisplayPoint | null
}

/**
 * Kiosk object
 * https://docs.ogc.org/cs/20-094/kiosk/index.html
 */
export interface Kiosk extends NamedFeature<LevelProperties> {
    id: KioskId,
    feature_type: FeatureType.kiosk,
    geometry: Polygon,
    properties: KioskProperties
}

export interface LevelProperties extends NamedFeatureProperties {
    category: LEVEL_CATEGORY,
    restriction: RESTRICTION_CATEGORY | null,
    outdoor: boolean,
    ordinal: number,
    name: Labels,
    short_name: Labels,
    display_point: DisplayPoint | null,
    address_id: AddressId | null,
    building_ids: Array<BuildingId> | null
}

/**
 * Level object
 * https://docs.ogc.org/cs/20-094/Level/index.html
 */
export interface Level extends NamedFeature<LevelProperties> {
    id: LevelId,
    feature_type: FeatureType.level,
    geometry: Polygon,
    properties: LevelProperties
}

/**
 * Occupant object
 * https://docs.ogc.org/cs/20-094/Occupant/index.html
 */
export interface Occupant extends Feature {
    id: OccupantId,
    feature_type: FeatureType.occupant,
    geometry: null,
    properties: FeatureProperties & {
        name: Labels,
        category: OCCUPANT_CATEGORY,
        anchor_id: AnchorId,
        hours: Hours | null,
        phone: Phone | null,
        website: Website | null,
        validity: Temporality | null,
        correlation_id: OccupantId | null
    }
}

/**
 * Opening object
 * https://docs.ogc.org/cs/20-094/Opening/index.html
 */
export interface Opening extends LabeledFeature {
    id: OpeningId,
    feature_type: FeatureType.opening,
    geometry: LineString,
    properties:  LabeledFeatureProperties & {
        category: OPENING_CATEGORY,
        accessibility: ACCESSIBILITY_CATEGORY | null,
        access_control: ACCESS_CONTROL_CATEGORY | null,
        door: Door | null,
        name: Labels | null,
        alt_name: Labels | null,
        display_point: DisplayPoint | null,
        level_id: LevelId
    }
}

/**
 * Relationship object
 * https://docs.ogc.org/cs/20-094/Relationship/index.html
 */
export interface Relationship extends Feature {
    id: RelationshipId,
    feature_type: FeatureType.relationship,
    geometry: Geometry | null,
    properties:  FeatureProperties & {
        category: RELATIONSHIP_CATEGORY,
        direction: "directed" | "undirected",
        origin: FeatureReference | null,
        intermediary: FeatureReference | null,
        destination: FeatureReference | null,
        hours: Hours | null
    }
}

/**
 * Section object
 * https://docs.ogc.org/cs/20-094/Section/index.html
 */
export interface Section extends LabeledFeature {
    id: SectionId,
    feature_type: FeatureType.section,
    geometry: Polygon,
    properties: LabeledFeatureProperties & {
        category: SECTION_CATEGORY,
        restriction: RESTRICTION_CATEGORY | null,
        accessibility: ACCESSIBILITY_CATEGORY | null,
        name: Labels | null,
        alt_name: Labels | null,
        display_point: DisplayPoint | null,
        level_id: LevelId,
        address_id: AddressId | null,
        correlation_id: SectionId | null,
        parents: SectionId | null
    }
}

export interface UnitProperties extends LabeledFeatureProperties {
    category: UNIT_CATEGORY,
    restriction: RESTRICTION_CATEGORY | null,
    accessibility: ACCESSIBILITY_CATEGORY | null,
    name: Labels | null,
    alt_name: Labels | null,
    level_id: LevelId,
    display_point: DisplayPoint | null
}

/**
 * Unit object
 * https://docs.ogc.org/cs/20-094/Unit/index.html
 */
export interface Unit extends LabeledFeature<UnitProperties> {
    id: UnitId,
    feature_type: FeatureType.unit,
    geometry: Polygon,
    properties: UnitProperties
}

/**
 * Venue object
 * https://docs.ogc.org/cs/20-094/Venue/index.html
 */
export interface Venue extends LabeledFeature {
    id: VenueId,
    feature_type: FeatureType.venue,
    geometry: Polygon,
    properties: FeatureProperties & {
        category: VENUE_CATEGORY,
        restriction: RESTRICTION_CATEGORY | null,
        name: Labels,
        alt_name: Labels | null,
        hours: Hours | null,
        phone: Phone | null,
        website: Website | null,
        display_point: DisplayPoint,
        address_id: AddressId
    }
}

// GEOMETRIC OBJECTS
export interface DisplayPoint extends Point {

}

/**
 * Access control categories
 * https://docs.ogc.org/cs/20-094/Categories/index.html#access-control
 */
export enum ACCESS_CONTROL_CATEGORY {
    "badgereader"="badgereader",
    "fingerprintreader"="fingerprintreader",
    "guard"="guard",
    "keyaccess"="keyaccess",
    "outofservice"="outofservice",
    "passwordaccess"="passwordaccess",
    "retinascanner"="retinascanner",
    "voicerecognition"="voicerecognition"
}

// CATEGORIES
/**
 * Accessibility categories
 * https://docs.ogc.org/cs/20-094/Categories/index.html#accessibility
 */
export enum ACCESSIBILITY_CATEGORY {
    "assisted.listening"="assisted.listening",
    braille="braille",
    hearing="hearing",
    hearingloop="hearingloop",
    signlanginterpreter="signlanginterpreter",
    tactilepaving="tactilepaving",
    tdd="tdd",
    trs="trs",
    volume="volume",
    wheelchair="wheelchair"
}

/**
 * Amenity categories
 * https://docs.ogc.org/cs/20-094/Categories/index.html#amenity
 */
export enum AMENITY_CATEGORY {
    amphitheater="amphitheater",
    animalreliefarea="animalreliefarea",
    arrivalgate="arrivalgate",
    atm="atm",
    babychanging="babychanging",
    baggagecarousel="baggagecarousel",
    "baggagecarousel.intl"="baggagecarousel.intl",
    baggagecarts="baggagecarts",
    baggageclaim="baggageclaim",
    "baggageclaim.oversize"="baggageclaim.oversize",
    baggagerecheck="baggagerecheck",
    baggagestorage="baggagestorage",
    boardinggate="boardinggate",
    "boardinggate.aircraft"="boardinggate.aircraft",
    "boardinggate.bus"="boardinggate.bus",
    "boardinggate.ferry"="boardinggate.ferry",
    "boardinggate.train"="boardinggate.train",
    bus="bus",
    "bus.muni"="bus.muni",
    "bus.national"="bus.national",
    businesscenter="businesscenter",
    cabin="cabin",
    caregiver="caregiver",
    carrental="carrental",
    cashier="cashier",
    changemachine="changemachine",
    checkin="checkin",
    "checkin.desk"="checkin.desk",
    "checkin.desk.oversizebaggage"="checkin.desk.oversizebaggage",
    "checkin.desk.transfer"="checkin.desk.transfer",
    "checkin.selfservice"="checkin.selfservice",
    childplayarea="childplayarea",
    coinlocker="coinlocker",
    copymachine="copymachine",
    defibrillator="defibrillator",
    drinkingfountain="drinkingfountain",
    eatingdrinking="eatingdrinking",
    elevator="elevator",
    emergencyshelter="emergencyshelter",
    entry="entry",
    escalator="escalator",
    exhibit="exhibit",
    faregate="faregate",
    "faregate.oversized"="faregate.oversized",
    fieldofplay="fieldofplay",
    "fieldofplay.americanfootball"="fieldofplay.americanfootball",
    "fieldofplay.baseball"="fieldofplay.baseball",
    "fieldofplay.basketball"="fieldofplay.basketball",
    "fieldofplay.fieldhockey"="fieldofplay.fieldhockey",
    "fieldofplay.icehockey"="fieldofplay.icehockey",
    "fieldofplay.rugby"="fieldofplay.rugby",
    "fieldofplay.soccer"="fieldofplay.soccer",
    "fieldofplay.softball"="fieldofplay.softball",
    "fieldofplay.tennis"="fieldofplay.tennis",
    "fieldofplay.trackfield"="fieldofplay.trackfield",
    "fieldofplay.volleyball"="fieldofplay.volleyball",
    "firealarmpullstation"="firealarmpullstation",
    "fireextinguisher"="fireextinguisher",
    firstaid="firstaid",
    fittingroom="fittingroom",
    foodservice="foodservice",
    gatearea="gatearea",
    groundtransportation="groundtransportation",
    guestservices="guestservices",
    handsanitizerstation="handsanitizerstation",
    healthscreening="healthscreening",
    hoteling="hoteling",
    immigration="immigration",
    information="information",
    "information.bid"="information.bid",
    "information.carrental"="information.carrental",
    "information.hotel"="information.hotel",
    "information.mufid"="information.mufid",
    "information.mufid.arrivals"="information.mufid.arrivals",
    "information.mufid.departures"="information.mufid.departures",
    "information.transit"="information.transit",
    landmark="landmark",
    library="library",
    limo="limo",
    lostandfound="lostandfound",
    mailbox="mailbox",
    meditation="meditation",
    meetingpoint="meetingpoint",
    mobilityrescue="mobilityrescue",
    mothersroom="mothersroom",
    movingwalkway="movingwalkway",
    paidarea="paidarea",
    parkandride="parkandride",
    parking="parking",
    "parking.bicycle"="parking.bicycle",
    "parking.compact"="parking.compact",
    "parking.ev"="parking.ev",
    "parking.longterm"="parking.longterm",
    "parking.motorcycle"="parking.motorcycle",
    "parking.shortterm"="parking.shortterm",
    "parking.waitingarea"="parking.waitingarea",
    payphone="payphone",
    pedestriancrossing="pedestriancrossing",
    peoplemover="peoplemover",
    phone="phone",
    "phone.emergency"="phone.emergency",
    photobooth="photobooth",
    platform="platform",
    police="police",
    powerchargingstation="powerchargingstation",
    prayerroom="prayerroom",
    "prayerroom.buddhism"="prayerroom.buddhism",
    "prayerroom.christianity"="prayerroom.christianity",
    "prayerroom.hinduism"="prayerroom.hinduism",
    "prayerroom.islam"="prayerroom.islam",
    "prayerroom.islam.female"="prayerroom.islam.female",
    "prayerroom.islam.male"="prayerroom.islam.male",
    "prayerroom.judaism"="prayerroom.judaism",
    "prayerroom.shintoism"="prayerroom.shintoism",
    "prayerroom.sikh"="prayerroom.sikh",
    "prayerroom.taoic"="prayerroom.taoic",
    privatelounge="privatelounge",
    productreturn="productreturn",
    "rail.muni"="rail.muni",
    "rail.national"="rail.national",
    ramp="ramp",
    "reception.desk"="reception.desk",
    recreation="recreation",
    restroom="restroom",
    "restroom.family"="restroom.family",
    "restroom.female"="restroom.female",
    "restroom.female.wheelchair"="restroom.female.wheelchair",
    "restroom.male"="restroom.male",
    "restroom.male.wheelchair"="restroom.male.wheelchair",
    "restroom.transgender"="restroom.transgender",
    "restroom.transgender.wheelchair"="restroom.transgender.wheelchair",
    "restroom.unisex"="restroom.unisex",
    "restroom.unisex.wheelchair"="restroom.unisex.wheelchair",
    "restroom.wheelchair"="restroom.wheelchair",
    rideshare="rideshare",
    seat="seat",
    seating="seating",
    security="security",
    "security.checkpoint"="security.checkpoint",
    "security.inspection"="security.inspection",
    service="service",
    shower="shower",
    shuttle="shuttle",
    sleepbox="sleepbox",
    smokingarea="smokingarea",
    stairs="stairs",
    storage="storage",
    strollerrental="strollerrental",
    studentadmissions="studentadmissions",
    studentservices="studentservices",
    swimmingpool="swimmingpool",
    "swimmingpool.children"="swimmingpool.children",
    "swimmingpool.family"="swimmingpool.family",
    taxi="taxi",
    ticketing="ticketing",
    "ticketing.airline"="ticketing.airline",
    "ticketing.bus"="ticketing.bus",
    "ticketing.bus.muni"="ticketing.bus.muni",
    "ticketing.bus.national"="ticketing.bus.national",
    "ticketing.rail"="ticketing.rail",
    "ticketing.rail.muni"="ticketing.rail.muni",
    "ticketing.rail.national"="ticketing.rail.national",
    "ticketing.shuttle"="ticketing.shuttle",
    traintrack="traintrack",
    transit="transit",
    unspecified="unspecified",
    valet="valet",
    vendingmachine="vendingmachine",
    "vendingmachine.trainticket"="vendingmachine.trainticket",
    wheelchairassist="wheelchairassist",
    wifi="wifi",
    yoga="yoga"
}

/**
 * Building categories
 * https://docs.ogc.org/cs/20-094/Categories/index.html#building
 */
export enum BUILDING_CATEGORY {
    parking="parking",
    transit="transit",
    "transit.bus"="transit.bus",
    "transit.train"="transit.train",
    unspecified="unspecified"
}

/**
 * Door categories
 * https://docs.ogc.org/cs/20-094/Categories/index.html#door
 */

export enum DOOR_CATEGORY {
    door="door",
    movablepartition="movablepartition",
    open="open",
    revolving="revolving",
    shutter="shutter",
    sliding="sliding",
    swinging="swinging",
    turnstile="turnstile",
    "turnstile.fullheight"="turnstile.fullheight",
    "turnstile.waistheight"="turnstile.waistheight",
    unspecified="unspecified"
}

/**
 * Door types
 * https://docs.ogc.org/cs/20-094/Reference/index.html#door
 */
export enum DOOR_TYPE {
    movablepartition="movablepartition",
    open="open",
    revolving="revolving",
    shutter="shutter",
    sliding="sliding",
    swinging="swinging",
    turnstile="turnstile",
    "turnstile.fullheight"="turnstile.fullheight",
    "turnstile.waistheight"="turnstile.waistheight"
}

/**
 * Fixture categories
 *
 */
export enum FIXTURE_CATEGORY {
    baggagecarousel="baggagecarousel",
    "boardinggate.desk"="boardinggate.desk",
    "checkin.desk"="checkin.desk",
    "checkin.kiosk"="checkin.kiosk",
    desk="desk",
    equipment="equipment",
    furniture="furniture",
    "immigration.desk"="immigration.desk",
    "inspection.desk"="inspection.desk",
    obstruction="obstruction",
    securityequipment="securityequipment",
    stage="stage",
    vegetation="vegetation",
    wall="wall"
}

/**
 * Footprint categories
 * https://docs.ogc.org/cs/20-094/Categories/index.html#footprint
 */
export enum FOOTPRINT_CATEGORY {
    aerial="aerial",
    ground="ground",
    subterranean="subterranean"
}

/**
 * Geofence categories
 * https://docs.ogc.org/cs/20-094/Categories/index.html#geofence
 */
export enum GEOFENCE_CATEGORY {
    concourse="concourse",
    geofence="geofence",
    paidarea="paidarea",
    platform="platform",
    postsecurity="postsecurity",
    presecurity="presecurity",
    terminal="terminal",
    underconstruction="underconstruction"
}

/**
 * Level categories
 * https://docs.ogc.org/cs/20-094/Categories/index.html#level
 */
export enum LEVEL_CATEGORY {
    arrivals="arrivals",
    "arrivals.domestic"="arrivals.domestic",
    "arrivals.intl"="arrivals.intl",
    departures="departures",
    "departures.domestic"="departures.domestic",
    "departures.intl"="departures.intl",
    parking="parking",
    transit="transit",
    unspecified="unspecified"
}

/**
 * Occupant categories
 * https://docs.ogc.org/cs/20-094/Categories/index.html#occupant
 */
export enum OCCUPANT_CATEGORY {
    "3dprinting",
    acai,
    accessories,
    accounting,
    acnetreatment,
    acupuncture,
    adoptionservices,
    adulteducation,
    adultentertainment,
    adultstore,
    advertising,
    advisoryservices,
    afghani,
    african,
    agritourism,
    airfield,
    airline,
    "airport.regional",
    airportloungebar,
    airportshuttle,
    airsoft,
    allergies,
    alternativemedicine,
    "american.modern",
    amusementpark,
    "amusementpark.ride",
    animalshelter,
    antiques,
    apmstop,
    appliances,
    arabian,
    "arabian.pizza",
    arcade,
    archery,
    architecture,
    argentine,
    armenian,
    artgallery,
    artinstruction,
    "arts.entertainment",
    artsandcrafts,
    artschool,
    artstudio,
    "artstudio.rental",
    artsupplies,
    asianfusion,
    astrologist,
    asturian,
    atm,
    "atm.cryptocurrency",
    audiovideoequipment,
    auditory,
    australian,
    "australian.modern",
    austrian,
    "austrian.schnitzel",
    "auto.accessibilityequipment",
    "auto.bodyshop",
    "auto.carbuyer",
    "auto.carshare",
    "auto.carwash",
    "auto.dealer.boat",
    "auto.dealer.car",
    "auto.dealer.motorcycle",
    "auto.dealer.rv",
    "auto.dentrepair.mobile",
    "auto.detailing",
    "auto.electric",
    "auto.evcharge",
    "auto.evcharge.dcfast",
    "auto.evcharge.tesla",
    "auto.glass",
    "auto.oilchange",
    "auto.parts",
    "auto.repair",
    "auto.repair.transmission",
    "auto.repair.wheelrim",
    "auto.repair.windshield",
    "auto.servicestation",
    "auto.shipping",
    "auto.stereoinstallation",
    "auto.tires",
    "auto.upholstery",
    automotive,
    autopartssupplies,
    babyclothesandsupplies,
    bagels,
    bakedgoods,
    ballonservices,
    bangladeshi,
    bank,
    bar,
    barbecue,
    barber,
    barfood,
    barreclass,
    baseballfield,
    bathingarea,
    batteries,
    battingcages,
    beach,
    beautysalon,
    beautyspas,
    bedbreakfast,
    beerbar,
    beergarden,
    beerhall,
    beerwineandspirits,
    beerwinespirits,
    beisl,
    belgian,
    "belgian.flemish",
    bengali,
    beveragestore,
    "bicycle.repair",
    bicyclerental,
    bicycleshop,
    bikesandequipment,
    billingservices,
    bingo,
    biryani,
    bistro,
    blacksea,
    blinds,
    blooddonation,
    blooddonationcenter,
    bodycontouring,
    bodypiercing,
    books,
    booksmagazinesmusicvideo,
    botanicalgarden,
    bowlingalley,
    boxing,
    brazilian,
    "brazilian.centralbrazil",
    "brazilian.empanadas",
    "brazilian.northeasternbrazil",
    "brazilian.northernbrazil",
    breakfastandbrunch,
    brewery,
    brewpub,
    bridalstore,
    british,
    bubbletea,
    buffet,
    buildingsupplies,
    bulgarian,
    bulkmedicalbilling,
    bungeejumping,
    burgers,
    burmese,
    businesscampus,
    businessconsulting,
    busrental,
    busstop,
    butcher,
    cabinets,
    cafe,
    cafeteria,
    cajun,
    cakes,
    calligraphy,
    cambodian,
    "canadian.modern",
    candy,
    "candy.dagashi",
    cannabisdispensary,
    canteen,
    cardioclasses,
    cardiology,
    "cards.stationery",
    careercounseling,
    caribbean,
    caricaturist,
    carouselride,
    carpet,
    carrental,
    catering,
    cellphoneaccessories,
    challengecourse,
    champagnebar,
    cheese,
    cheesesteaks,
    chickenshop,
    chickenwings,
    childbirthschool,
    childcare,
    chilean,
    chimneycakes,
    chinese,
    "chinese.cantonese",
    "chinese.dimsum",
    "chinese.fuzhou",
    "chinese.hainan",
    "chinese.hakka",
    "chinese.henghwa",
    "chinese.hokkien",
    "chinese.hunan",
    "chinese.pekinese",
    "chinese.shanghainese",
    "chinese.szechuan",
    "chinese.teochew",
    chinesebazaar,
    chiropractic,
    chocolate,
    christmastrees,
    churros,
    cider,
    cigarbar,
    cinema,
    cityhall,
    climbing,
    clinic,
    clockrepair,
    clothing,
    "clothing.bespoke",
    "clothing.childrens",
    "clothing.mens",
    "clothing.plussize",
    "clothing.womens",
    cocktailbar,
    coffee,
    "coffee.tea",
    coffeeroaster,
    coffeeteasupplies,
    coincashingkiosk,
    college,
    colombian,
    comedyclub,
    comfortfood,
    comicbooks,
    commercialrealestate,
    commissionedartists,
    communitybookbox,
    communitycenter,
    computersandaccessories,
    conceptshop,
    concourse,
    condominium,
    congee,
    constructionequipmentrental,
    contractors,
    conveniencestore,
    conveyorsushi,
    "cooking.instruction",
    cookingschool,
    copyshop,
    corporateheadquarters,
    corporateoffices,
    corsican,
    cosmetics,
    cosmeticsurgery,
    cosmetologyschool,
    costumes,
    countertopinstallation,
    countryclub,
    courier,
    crepes,
    cryotherapy,
    cuban,
    culturalcenter,
    cupcakes,
    currencyexchange,
    customcakes,
    custommerchandise,
    cyclingclass,
    cypriot,
    czech,
    danceclub,
    danceschool,
    dancestudio,
    dancewear,
    danish,
    datarecovery,
    dayspa,
    "dealer.usedvehicle",
    delicatessen,
    "delicatessen.sandwiches",
    dentalhygiene,
    dentistry,
    "dentistry.cosmetic",
    "dentistry.general",
    "dentistry.pediatric",
    departmentstore,
    deptartmentstore,
    dermatology,
    desserts,
    diagnosticimaging,
    diagnosticservices,
    dialysis,
    dietician,
    digitizingservices,
    diner,
    dinnertheater,
    discountstore,
    distillery,
    divebar,
    diyfood,
    dmv,
    dominican,
    donair,
    donationcenter,
    donuts,
    doorsalesandinstallation,
    drivingrange,
    drivingschool,
    drycleaning,
    drycleaninglaundry,
    dumplings,
    dumpsterrental,
    dutyfree,
    earnosethroat,
    easterneuropean,
    eatertainment,
    editorialservices,
    education,
    educationservices,
    egyptian,
    electricians,
    electronicappliances,
    electronicparts,
    electronicsrepair,
    elementaryschool,
    embroiderycrochet,
    emergencymedicine,
    emissionstesting,
    empanadas,
    employmentagency,
    endodontics,
    engraving,
    escapegame,
    ethiopian,
    ethnicgrocerystore,
    "european.modern",
    eventplanning,
    eventspace,
    experiences,
    eyelashes,
    "eyewear.opticians",
    fabricstore,
    fairground,
    falafel,
    familyfriendly,
    familyfuncenter,
    familymedicine,
    familyplanning,
    familyrestaurant,
    farm,
    farmersmarket,
    fashion,
    fashionaccessories,
    fastfood,
    fencing,
    fengshui,
    ferry,
    fieldofplay,
    filipino,
    financialservices,
    fingerprinting,
    firearmstrainingschool,
    fish,
    fishandchips,
    fitnessbootcamp,
    fitnessequipment,
    fitnessinstruction,
    fixedbaseoperator,
    flatbread,
    flightinstructionschool,
    floatspa,
    flooringinstallationandrepair,
    floraldesign,
    florist,
    florists,
    flowers,
    fondue,
    foodcourt,
    fooddelivery,
    foodstand,
    foodtruck,
    formalwear,
    "formalwear.rental",
    freiduria,
    french,
    "french.alsatian",
    "french.auvergnat",
    "french.baguette",
    "french.berrichon",
    "french.bourguignon",
    "french.brasserie",
    "french.lyonnais",
    "french.nicois",
    "french.provencal",
    friterie,
    frozenfoods,
    fruitandvegetables,
    fuelstation,
    funeralservices,
    furclothing,
    furniture,
    "furniture.rental",
    furniturestore,
    gardening,
    gastroenterology,
    gastropubs,
    gelato,
    georgian,
    german,
    "german.baden",
    "german.bavarian",
    "german.currysausage",
    "german.easterngerman",
    "german.fischbroetchen",
    "german.franconian",
    "german.hessian",
    "german.heuriger",
    "german.northerngerman",
    "german.palatine",
    "german.rhinelandian",
    "german.swabian",
    "giblets",
    "giftshops",
    "glutenfree",
    "gokarting",
    "goldmerchants",
    "golf",
    "golf.instruction",
    "golfequipment",
    "golfshop",
    "gourmetfood",
    "gourmetmarket",
    "graphicaldesign",
    "greek",
    "grillingequipment",
    "grocery",
    "grocery.asian",
    "grocery.chinese",
    "grocery.indian",
    "grocery.japanese",
    "grocery.korean",
    "grocery.persian",
    "grocerystore",
    "guitarstore",
    "gunrange",
    "gunsandammo",
    "gym",
    "gymnastics",
    "hairblowout",
    "haircutsstyling",
    "haircutsstyling.mens",
    "hairextensions",
    "hairloss",
    "hairremoval",
    "hairremoval.laser",
    "hairremoval.threading",
    "hairremoval.waxing",
    "hairstylist",
    "haitian",
    "halal",
    "hardware",
    "hats",
    "hauntedhouse",
    "hawaiian",
    "headshop",
    "healthcare",
    "healthcarecenter",
    "healthyfoods",
    "hearingaidproviders",
    "hearingaids",
    "hennaartist",
    "herbalmedicine",
    "herbsandspices",
    "highschool",
    "himalayan",
    "hobbyshop",
    "holidaydecorations",
    "homeandgarden",
    "homeappliancerepair",
    "homeautomation",
    "homecleaning",
    "homedecor",
    "homedevelopers",
    "homegarden",
    "homehealthcare",
    "homeopathy",
    "hometheaterinstallation",
    "honey",
    "hongkong.cafe",
    "hookahbar",
    "horsequipment",
    "hospital",
    "hostel",
    "hotdogs",
    "hotel",
    "hotel.business",
    "hotel.capsule",
    "hotelbar",
    "hotpot",
    "hottubandpool",
    "housingcooperative",
    "hungarian",
    "huntingfishingsupplies",
    "hvac",
    "hypermarket",
    "iberian",
    "icecream",
    "importedfood",
    "indian",
    "indian.andhra",
    "indian.assamese",
    "indian.awadhi",
    "indian.bihari",
    "indian.chettinad",
    "indian.goan",
    "indian.gujarat",
    "indian.hyderabadi",
    "indian.kerala",
    "indian.konkan",
    "indian.lucknowi",
    "indian.maharashtrian",
    "indian.malwani",
    "indian.mangalorean",
    "indian.northindian",
    "indian.oriya",
    "indian.rajasthani",
    "indian.southindian",
    "indonesian",
    "informationtechnology",
    "installmentloanservices",
    "insulationinstallation",
    "insurance",
    "insurance.auto",
    "insurance.health",
    "insurance.home",
    "insurance.life",
    "interiordesign",
    "internalmedicine",
    "internationalfood",
    "internetbooth",
    "internetcafe",
    "internetserviceprovider",
    "investmentbanking",
    "irish",
    "irishpub",
    "israeli",
    "italian",
    "italian.abruzzese",
    "italian.altoatesine",
    "italian.apulian",
    "italian.calabrian",
    "italian.cucinacampana",
    "italian.diner",
    "italian.emilian",
    "italian.friulan",
    "italian.lumbard",
    "italian.napoletana",
    "italian.norcinerie",
    "italian.piedmont",
    "italian.roman",
    "italian.sardinian",
    "italian.sicilian",
    "italian.tuscan",
    "italian.venetian",
    "ivhydration",
    "izakaya",
    "japanese",
    "japanese.bento",
    "japanese.blowfish",
    "japanese.curry",
    "japanese.donburi",
    "japanese.gyudon",
    "japanese.handrolls",
    "japanese.horumon",
    "japanese.kushikatsu",
    "japanese.nikkei",
    "japanese.oden",
    "japanese.okonomiyaki",
    "japanese.onigiri",
    "japanese.oyakodon",
    "japanese.ramen",
    "japanese.shabushabu",
    "japanese.soba",
    "japanese.sukiyaki",
    "japanese.takoyaki",
    "japanese.tempura",
    "japanese.teppanyaki",
    "japanese.tonkatsu",
    "japanese.udon",
    "japanese.unagi",
    "japanese.westernjapanese",
    "japanese.yakiniku",
    "japanese.yakitori",
    "japanesesweets",
    "jewelry",
    "jewelryrepair",
    "jewish",
    "juicebar",
    "kaiseki",
    "karaoke",
    "kashmiri",
    "kebab",
    "kidsactivities",
    "kimonos",
    "kindergarten",
    "kiosk",
    "kiosk.food",
    "kitchenandbath",
    "kitchenincubator",
    "knifesharpening",
    "knittingsupplies",
    "kopitiam",
    "korean",
    "kosher",
    "kurdish",
    "laboratorytesting",
    "landmark",
    "landscaping",
    "languageschool",
    "laotian",
    "lasereyesurgery",
    "lasertag",
    "latinamerican",
    "laundromat",
    "laundryservices",
    "lawyer",
    "lawyer.business",
    "lawyer.criminaldefense",
    "lawyer.divorce",
    "lawyer.estateplanning",
    "lawyer.immigration",
    "lawyer.litigation",
    "lawyer.personalinjury",
    "lawyer.realestate",
    "lawyer.tax",
    "lawyer.willtrustprobate",
    "lawyer.workerscomp",
    "leathergoods",
    "lebanese",
    "legalservices",
    "library",
    "lifecoach",
    "lighting",
    "ligurian",
    "limo",
    "linens",
    "lingerie",
    "livestocksales",
    "localservices",
    "locksmith",
    "lotterystand",
    "loungebar",
    "luggage",
    "luggagestorage",
    "macaron",
    "magicians",
    "mailboxcenter",
    "makeupartist",
    "malaysian",
    "mamak",
    "manicurists",
    "marketing",
    "martialarts",
    "massageschool",
    "massagetherapist",
    "massagetherapy",
    "maternitywear",
    "mattresses",
    "mauritian",
    "meatballs",
    "medicalcenter",
    "medicalspa",
    "medicalsupplies",
    "mediterranean",
    "mexican",
    "mexican.easternmexican",
    "mexican.jaliscan",
    "mexican.modern",
    "mexican.northernmexican",
    "mexican.oaxacan",
    "mexican.pueblan",
    "mexican.yucatan",
    "middleeastern",
    "militarybase",
    "milkbar",
    "milkshakes",
    "minigolf",
    "mobilephonerepair",
    "mobilephones",
    "moneytransferservices",
    "mongolian",
    "moroccan",
    "mortgagebroker",
    "motorcyclingclothing",
    "movierental.kiosk",
    "mughlai",
    "museum.art",
    "museum.children",
    "museum.history",
    "musicalinstruments",
    "musicalinstrumentservices",
    "musicvenue",
    "musicvideo",
    "naga",
    "nasilemak",
    "naturopathy",
    "nepalese",
    "newspapersandmagazines",
    "newzealand",
    "nicaraguan",
    "nightfood",
    "nonprofit",
    "noodles",
    "northamerican.traditional",
    "norwegian",
    "notarypublic",
    "nurseries.gardening",
    "nyonya",
    "obgyn",
    "observatory",
    "occupationaltherapy",
    "officebuilding",
    "officeequipmentandsupplies",
    "okinawan",
    "oliveoil",
    "opensandwiches",
    "opera.ballet",
    "opthamalogy",
    "opticians",
    "optometry",
    "oralsurgery",
    "organicfood",
    "oriental",
    "orthodontics",
    "orthopedics",
    "orthotics",
    "osteopathy",
    "ottoman",
    "outdoorfurniture",
    "outdoorgear",
    "outletmall",
    "outletstore",
    "oxygenbar",
    "pachinko",
    "packagelocker",
    "packing",
    "packingsupplies",
    "paella",
    "painmanagement",
    "paintandsip",
    "painting",
    "paintstores",
    "paintyourownpottery",
    "pakistani",
    "parentingschool",
    "parking",
    "parks",
    "parma",
    "parsi",
    "partycharacters",
    "partyequipment.rental",
    "partysupplies",
    "passportvisaservices",
    "pasta",
    "pathology",
    "pawn",
    "paydayloan",
    "pediatrics",
    "performingarts",
    "perfume",
    "periodontics",
    "permanentmakeup",
    "persian",
    "personalcare",
    "personalshopper",
    "personaltrainer",
    "peruvian",
    "pets",
    "pets.adoption",
    "pets.boarding",
    "pets.grooming",
    "pets.photography",
    "pets.sitting",
    "pets.training",
    "pets.transportation",
    "petstore",
    "petstore.fish",
    "petstore.reptile",
    "pharmacy",
    "pharmacystore",
    "phonechargingstation",
    "photobooth.rental",
    "photography",
    "photography.event",
    "photography.session",
    "photographyequipment",
    "photographystore",
    "physicaltherapy",
    "physician",
    "piadina",
    "pianobar",
    "pianostore",
    "pictureframing",
    "pilates",
    "pita",
    "pizza",
    "placeofworship",
    "placeofworship.church",
    "placeofworship.mosque",
    "placeofworship.synagogue",
    "placeofworship.unitarian",
    "planetarium",
    "plasticsurgery",
    "playcenter",
    "playground",
    "playsets",
    "plaza",
    "podiatrists",
    "podiatry",
    "poke",
    "poledancingschool",
    "policestation",
    "policestation.koban",
    "polish",
    "polish.pierogis",
    "poolcleaning",
    "poolhall",
    "pooltablesupplies",
    "popcorn",
    "popup",
    "popupshops",
    "portuguese",
    "portuguese.alentejo",
    "portuguese.algarve",
    "portuguese.azores",
    "portuguese.beira",
    "portuguese.fadohouse",
    "portuguese.madeira",
    "portuguese.minho",
    "portuguese.ribatejo",
    "portuguese.trasosmontes",
    "postoffice",
    "postoffice.authorizedagent",
    "potatoes",
    "poutineries",
    "prenatal",
    "preschool",
    "pretzels",
    "preventivemedicine",
    "printmedia",
    "privateinvestigation",
    "privatejetcharter",
    "privateschool",
    "privateshuttlebus",
    "professionalservices",
    "professionalsportsteam",
    "propertymanagement",
    "psychiatrists",
    "psychiatry",
    "psychic",
    "psychology",
    "pub",
    "publicart",
    "publiclibrary",
    "publicservices.government",
    "publictransport",
    "puertorican",
    "pulmonology",
    "punjabi",
    "racetrack",
    "radiology",
    "radiostation",
    "rawfood",
    "realestate.agents",
    "realestate.services",
    "realestateagents",
    "realestateagents.commercial",
    "realestateservices",
    "recordingstudio",
    "recreation",
    "recreationcenter",
    "recyclingcenter",
    "reflexology",
    "religiousitems",
    "rental.videoandgame",
    "researchanddevelopment",
    "residentialapartments",
    "restaurant",
    "retirementhome",
    "reunionnese",
    "reupholstery",
    "riceshop",
    "rideshare",
    "robatayaki",
    "rockclimbing",
    "rodizio",
    "romanian",
    "roofing",
    "rotisseriechicken",
    "rugs",
    "russian",
    "sakebar",
    "salad",
    "salvadoran",
    "sandwiches",
    "sauna",
    "scandinavian",
    "scandinaviandesign",
    "school",
    "scottish",
    "screenprinting",
    "screenprinting.tshirt",
    "seafood",
    "seafoodmarket",
    "securitysystems",
    "selfstorage",
    "senegalese",
    "seniorcenter",
    "serbianandcroatian",
    "sewingalterations",
    "sharedofficespace",
    "shavedice",
    "shavedsnow",
    "shippingcenters",
    "shippingdropbox",
    "shoerepair",
    "shoes",
    "shoeshine",
    "shoestore",
    "shopping",
    "shoppingpassage",
    "shutterinstallation",
    "signature",
    "signmaking",
    "silentdisco",
    "singaporean",
    "skatepark",
    "skatingequipment",
    "skatingrink",
    "skiequipment",
    "skincare",
    "skydiving",
    "sleepwear",
    "slovakian",
    "soccer",
    "socialclub",
    "socialservices",
    "softwaredevelopment",
    "solarinstallation",
    "sommeliers",
    "soulfood",
    "soup",
    "southafrican",
    "southernunitedstates",
    "southwestunitedstates",
    "souvenirs",
    "spanish",
    "spanish.andalusian",
    "spanish.basque",
    "spanish.catalan",
    "spanish.galician",
    "specialtyfood",
    "specialtyschool",
    "spinclass",
    "spiritualproducts",
    "sportinggoods",
    "sportsbar",
    "sportsclub",
    "sportsequipment.rental",
    "sportsgoods",
    "sportsmedicine",
    "sportsschool",
    "sportswear",
    "srilankan",
    "stationery",
    "steak",
    "stockings",
    "streetvendor",
    "structuralengineers",
    "subwaystation",
    "supermarket",
    "supperclub",
    "surfacerefinishing",
    "surfing",
    "surfingequipment",
    "surgeon",
    "sushi",
    "swedish",
    "swedish.traditional",
    "swimminginstruction",
    "swimmingpool",
    "swimwear",
    "swiss",
    "syrian",
    "taberna",
    "tabletopgames",
    "tableware",
    "tacos",
    "taiwanese",
    "taiyaki",
    "talentagencies",
    "tamales",
    "tanningbeds",
    "tanningservices",
    "tapas",
    "tapas.smallplate",
    "tattoo",
    "tattoo.removal",
    "taxi",
    "taxistand",
    "taxoffice",
    "taxservices",
    "tea",
    "teachersupplies",
    "teambuilding",
    "teethwhitening",
    "telecommunications",
    "televisionserviceproviders",
    "televisionstation",
    "tennis.instruction",
    "terminal",
    "terminal.bus",
    "testpreparationschool",
    "texmex",
    "thai",
    "theater.drivein",
    "theater.movie",
    "themedcafe",
    "thriftstore",
    "tibetan",
    "tickets",
    "tikibar",
    "titleloan",
    "tobaccoshop",
    "tofu",
    "touristattraction",
    "tours",
    "tours.boat",
    "tours.bus",
    "tours.scooter",
    "tours.walking",
    "towncarservice",
    "toys",
    "toystore",
    "traditionalchinesemedicine",
    "trainserviceprovider",
    "trainstation",
    "trampolining",
    "transitlounge",
    "translationservices",
    "transportationservices",
    "trattoria",
    "travelagent",
    "travelservices",
    "trinidadian",
    "trophyshops",
    "truckrental",
    "tuina",
    "turkish",
    "turkish.cheekufta",
    "turkish.gozleme",
    "turkish.homemadefood",
    "turkish.lahmacun",
    "turkish.ravioli",
    "tutoring",
    "ukrainian",
    "uniforms",
    "urgentcare",
    "usedbooks",
    "utilities",
    "uzbek",
    "vacationhome",
    "vacationhome.agent",
    "valetservices",
    "vapeshops",
    "vascularmedicine",
    "vegan",
    "vegetarian",
    "vendingmachine",
    "vendingmachine.beverage",
    "venezuelan",
    "venison",
    "veteransorganization",
    "veterinarian",
    "videofilmproduction",
    "videogamesandconsoles",
    "vietnamese",
    "vintageclothing",
    "vinylrecords",
    "virtualreality",
    "visitorcenter",
    "vitaminssupplements",
    "vocalcoach",
    "vocationalschool",
    "waffles",
    "walkinclinic",
    "warehouse",
    "watches",
    "watchrepair",
    "waterpark",
    "waterpurification",
    "webdesign",
    "weddingchappel",
    "weddingplanning",
    "weightloss",
    "welsh",
    "whiskeybar",
    "wholesalemerchant",
    "wholesaler",
    "wigs",
    "windowinstallation",
    "winebar",
    "winery",
    "winetasting",
    "wok",
    "wraps",
    "yoga",
    "youthclub",
    "yugoslav"
}

/**
 * Opening categories
 * https://docs.ogc.org/cs/20-094/Categories/index.html#opening
 */
export enum OPENING_CATEGORY {
    "automobile"="automobile",
    "bicycle"="bicycle",
    "emergencyexit"="emergencyexit",
    "pedestrian"="pedestrian",
    "pedestrian.principal"="pedestrian.principal",
    "pedestrian.transit"="pedestrian.transit",
    "service"="service"
}

/**
 * Relationship categories
 * https://docs.ogc.org/cs/20-094/Categories/index.html#relationship
 */
export enum RELATIONSHIP_CATEGORY {
    "elevator"="elevator",
    "escalator"="escalator",
    "movingwalkway"="movingwalkway",
    "ramp"="ramp",
    "stairs"="stairs",
    "traversal"="traversal",
    "traversal.path"="traversal"
}

/**
 * Restricition categories
 * https://docs.ogc.org/cs/20-094/Categories/index.html#restriction
 */
export enum RESTRICTION_CATEGORY {
    employeesonly="employeesonly",
    restricted="restricted"
}

export enum SECTION_CATEGORY {
    arcade="arcade",
    baggageclaim="baggageclaim",
    "baggageclaim.intl"="baggageclaim.intl",
    carrental="carrental",
    "carrental.dropoff"="carrental.dropoff",
    checkin="checkin",
    concessions="concessions",
    cubicle="cubicle",
    dutyfree="dutyfree",
    eatingdrinking="eatingdrinking",
    entertainmentarea="entertainmentarea",
    "entertainmentarea.game"="entertainmentarea.game",
    "entertainmentarea.music"="entertainmentarea.music",
    "entertainmentarea.performance"="entertainmentarea.performance",
    "entertainmentarea.sport"="entertainmentarea.sport",
    exhibit="exhibit",
    exhibition="exhibition",
    gambling="gambling",
    "gambling.baccarat"="gambling.baccarat",
    "gambling.bingo"="gambling.bingo",
    "gambling.blackjack"="gambling.blackjack",
    "gambling.craps"="gambling.craps",
    "gambling.keno"="gambling.keno",
    "gambling.mahjong"="gambling.mahjong",
    "gambling.medalgame"="gambling.medalgame",
    "gambling.minibaccarat"="gambling.minibaccarat",
    "gambling.offtrackbetting"="gambling.offtrackbetting",
    "gambling.pachinko"="gambling.pachinko",
    "gambling.paigow"="gambling.paigow",
    "gambling.poker"="gambling.poker",
    "gambling.poker.letitride"="gambling.poker.letitride",
    "gambling.poker.paigow"="gambling.poker.paigow",
    "gambling.poker.threecard"="gambling.poker.threecard",
    "gambling.poker.video"="gambling.poker.video",
    "gambling.roulette"="gambling.roulette",
    "gambling.rummy"="gambling.rummy",
    "gambling.sicbo"="gambling.sicbo",
    "gambling.slotmachine"="gambling.slotmachine",
    "gambling.slotmachine.highlimit"="gambling.slotmachine.highlimit",
    gatearea="gatearea",
    "gatearea.holding"="gatearea.holding",
    immigration="immigration",
    "immigration.schengen"="immigration.schengen",
    information=information,
    paidarea="paidarea",
    parkandride="parkandride",
    parking="parking",
    "parking.bicycle"="parking.bicycle",
    "parking.compact"="parking.compact",
    "parking.ev"="parking.ev",
    "parking.longterm"="parking.longterm",
    "parking.motorcycle"="parking.motorcycle",
    "parking.shortterm"="parking.shortterm",
    "parking.waitingarea"="parking.waitingarea",
    platform="platform",
    postsecurity="postsecurity",
    presecurity="presecurity",
    private="private",
    recomposearea="recomposearea",
    recreation="recreation",
    rental="rental",
    retail="retail",
    retaildepartment="retaildepartment",
    road="road",
    seating="seating",
    seatingrow="seatingrow",
    security="security",
    servicearea="servicearea",
    ticketing="ticketing",
    vegetation="vegetation",
    walkway="walkway"
}

/**
 * Unit categories
 * https://docs.ogc.org/cs/20-094/Categories/index.html#unit
 */
export enum UNIT_CATEGORY {
    auditorium="auditorium",
    brick="brick",
    classroom="classroom",
    column="column",
    concrete="concrete",
    conferenceroom="conferenceroom",
    drywall="drywall",
    elevator="elevator",
    escalator="escalator",
    fieldofplay="fieldofplay",
    firstaid="firstaid",
    fitnessroom="fitnessroom",
    foodservice="foodservice",
    footbridge="footbridge",
    glass="glass",
    huddleroom="huddleroom",
    kitchen="kitchen",
    laboratory="laboratory",
    library="library",
    lobby="lobby",
    lounge="lounge",
    mailroom="mailroom",
    mothersroom="mothersroom",
    movietheater="movietheater",
    movingwalkway="movingwalkway",
    nonpublic="nonpublic",
    office="office",
    opentobelow="opentobelow",
    parking="parking",
    phoneroom="phoneroom",
    platform="platform",
    privatelounge="privatelounge",
    ramp="ramp",
    recreation="recreation",
    restroom="restroom",
    "restroom.family"="restroom.family",
    "restroom.female"="restroom.female",
    "restroom.female.wheelchair"="restroom.female.wheelchair",
    "restroom.male"="restroom.male",
    "restroom.male.wheelchair"="restroom.male.wheelchair",
    "restroom.transgender"="restroom.transgender",
    "restroom.transgender.wheelchair"="restroom.transgender.wheelchair",
    "restroom.unisex"="restroom.unisex",
    "restroom.unisex.wheelchair"="restroom.unisex.wheelchair",
    "restroom.wheelchair"="restroom.wheelchair",
    road="road",
    room="room",
    serverroom="serverroom",
    shower="shower",
    smokingarea="smokingarea",
    stairs="stairs",
    steps="steps",
    storage="storage",
    structure="structure",
    terrace="terrace",
    theater="theater",
    unenclosedarea="unenclosedarea",
    unspecified="unspecified",
    vegetation="vegetation",
    waitingroom="waitingroom",
    walkway="walkway",
    "walkway.island"="walkway.island",
    wood=wood
}

/**
 * Venue categories
 * https://docs.ogc.org/cs/20-094/Categories/index.html#venue
 */
export enum VENUE_CATEGORY {
    airport="airport",
    "airport.intl"="airport.intl",
    aquarium="aquarium",
    businesscampus="businesscampus",
    casino="casino",
    communitycenter="communitycenter",
    conventioncenter="conventioncenter",
    governmentfacility="governmentfacility",
    healthcarefacility="healthcarefacility",
    hotel="hotel",
    museum="museum",
    parkingfacility="parkingfacility",
    resort="resort",
    retailstore="retailstore",
    shoppingcenter="shoppingcenter",
    stadium="stadium",
    stripmall="stripmall",
    theater="theater",
    themepark="themepark",
    trainstation="trainstation",
    transitstation="transitstation",
    university="university"
}